'use client';

import DocumentViewer from './DocumentViewer';

const cip=[['General requirements','₱10,356,250.00','₱9,845,588.99','36.47%'],['Existing conditions','₱80,000.00','₱79,200.00','0.29%'],['Concrete works','₱16,563,750.00','₱15,838,010.00','58.66%']];
const additional=[['General requirements','₱295,000.00','₱206,500.00','2.58%'],['Scaffoldings','₱1,020,000.00','₱816,000.00','10.20%'],['Chipping of walls','₱510,000.00','₱372,300.00','4.65%'],['Plastering of walls','₱1,224,000.00','₱893,520.00','11.17%'],['Exterior dropwall visor','₱3,673,250.00','₱2,754,937.50','34.44%'],['Aircon ledges','₱102,000.00','₱66,300.00','0.83%'],['Balcony slab & zocallo','₱1,175,750.00','₱823,025.00','10.29%']];

function BillingTable({title,rows}:{title:string,rows:string[][]}){return <div className="regis-table"><div className="table-head"><span>{title}</span><span>BOQ TO PROGRESS VALUATION</span></div><div className="table-scroll"><table><thead><tr><th>Work package</th><th>BOQ amount</th><th>To-date amount</th><th>Weighted progress</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map((c,i)=><td key={c} className={i>0?'numeric':''}>{c}</td>)}</tr>)}</tbody></table></div></div>}

export default function TwoRegisCase(){
  const cipPages=Array.from({length:4},(_,i)=>`/images/documents/two-regis-cip/page-${i+1}.jpg`);
  const exteriorPages=Array.from({length:2},(_,i)=>`/images/documents/two-regis-exterior/page-${i+1}.jpg`);
  return <div className="regis-case">
    <div className="regis-hero"><div className="regis-image"><img src="/images/projects/megaworld-two-regis.webp" alt="Megaworld Two Regis residential tower at The Upper East"/><div><span>MEGAWORLD · THE UPPER EAST</span><b>Two Regis</b></div></div><div className="regis-copy"><span className="portfolio-kicker">BOQ · PROGRESS BILLING · COST CONTROL</span><h3>Two Regis</h3><p>Quantity surveying and progress valuation for exterior cast-in-place wall takeover works and subsequent façade rectification, ledges, dropwall visor, balcony slab and zocallo packages.</p><div className="ubiquity-facts"><div><b>Project</b><span>Two Regis · Upper East Residence 2</span></div><div><b>Location</b><span>The Upper East, Bacolod City</span></div><div><b>Role</b><span>QS / PM · BOQ management · Progress billing</span></div></div></div></div>
    <div className="regis-packages"><article><span>CIP CAST-IN-PLACE WALL PACKAGE</span><strong>₱27.00M</strong><div className="regis-progress"><i style={{width:'95.42%'}}/><b>95.42% cumulative</b></div><dl><div><dt>Billing</dt><dd>No. 14</dd></div><div><dt>This period</dt><dd>₱469,810.00</dd></div><div><dt>To date</dt><dd>₱25,762,798.99</dd></div></dl></article><article><span>EXTERIOR & ADDITIONAL WORKS</span><strong>₱8.00M</strong><div className="regis-progress"><i style={{width:'74.16%'}}/><b>74.16% cumulative</b></div><dl><div><dt>Billing</dt><dd>No. 3</dd></div><div><dt>This period</dt><dd>₱1,112,945.00</dd></div><div><dt>To date</dt><dd>₱5,932,582.50</dd></div></dl></article></div>
    <div className="regis-evidence"><div className="ubiquity-schedule-heading"><span>COMMERCIAL EVIDENCE</span><h4>BOQ values carried through to measured progress.</h4><p>The tables below summarize the original package value and evaluated cumulative accomplishment as of August 20, 2024. The evaluated work-package summaries are presented directly below.</p></div><BillingTable title="CIP · BILLING 14" rows={cip}/><BillingTable title="EXTERIOR WORKS · BILLING 3" rows={additional}/><DocumentViewer title="Two Regis — CIP Progress Billing No. 14" subtitle="Four-page cast-in-place wall progress evaluation presented inside the portfolio." pages={cipPages}/><DocumentViewer title="Two Regis — Exterior & Additional Works Billing No. 3" subtitle="Two-page progress evaluation for façade and additional works." pages={exteriorPages}/><p className="ubiquity-note">Progress-billing evidence dated August 30, 2024. Amounts and percentages are retained from the supplied evaluation documents.</p></div>
  </div>;
}
